### ISSUE TITLE
[Suggestion] Prevent the out of memory error

### ISSUE THREAD

**Issue by tiantz17** [zchwang/DeepRMSD-Vina_Optimization#2]
Hi, nice work!

I have met a memory issue when scoring a ligand pose using the scoring function.

[scripts/scoring_function.py#L229](https://github.com/zchwang/DeepRMSD-Vina_Optimization/blob/master/scripts/scoring_function.py#L229)

The matrix multiplication may sometimes cause an extremely large memory usage.

I used the following code to prevent it.

```
# original code
# matrix = torch.matmul(features, init_matrix)

# memory-efficient code
matrix = []
for i, (a,b) in enumerate(zip(features, init_matrix)):
    matrix.append(torch.matmul(a, b))
matrix = torch.cat(matrix, 0)
```

I hope this will be helpful to other people.

**Comment by zchwang** [comment]
Hi,

The size of features and init_matrix depends on the size of the protein and the ligand, as well as the number of concurrent processing ligand poses. When you don't have enough memory, you can try several ways to avoid memory explosions:

1.  Cut the protein. The atoms of the protein far away from the binding site have no effect on the binding of ligands.
2.  Reduce the number of ligands poses that run at the same time.

I hope this will help you.
