### ISSUE TITLE
clarification + gpu model

### ISSUE THREAD

**Issue by ricardojdgferreira** [zchwang/DeepRMSD-Vina_Optimization#3]
I am currently experimenting your code, and it's great.
I have some doubts though:

under optimization.py, can you clarify what is:
- patience
- delta
- torsion param

Also, do you have (or is it possible to retrain) a model to use GPU (thus to speed up calculations)?

Thanks!

**Comment by zchwang** [comment]
Hi,

Just like the earlystopping mechanism in the training process, we also define an "earlystopping" in the optimization process, that is, if the score does not decrease (delta score is less than "delta") after several steps ("patience"), the optimization stops.

The "torsion param" is a parameter used to describe the torsion scale of the rotatable bond of the ligand. 
Currently we have not updated the GPU version, and we will continue to improve our algorithm in the future.

I hope this will help you!

Best regards
